# Generated by Django 2.2.28 on 2025-01-31 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UploadingImages',
            new_name='ImageUpload',
        ),
    ]
