# Generated by Django 2.2.28 on 2025-02-01 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0003_category_page'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
